# These are supported funding model platforms

github: matthewjdegarmo # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: matthewjdegarmo # Replace with a single Patreon username
custom: ['https://donate.matthewjdegarmo.com', 'https://paypal.me/matthewjdegarmo'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
